// Flow TV — character library bridge.
//
// Flow TV's Phase 1 produces a "character reference" image used as an
// ingredient when each scene is rendered. This module exposes that image
// (and its accompanying prompt) through the existing NarrateAI `Character`
// DB model so users can browse and re-pick prior characters from the
// dashboard create-run UI.
//
// Storage layout:
//   - DB row: prisma `Character` with `type = "flow_tv"`, `name = <storyTitle>`,
//             `fullPrompt = <characterPrompt>`, `previewUrl = "/characters/<userId>/<charId>.png"`.
//   - File: copied from the run's `characterPath` into
//     `public/characters/<userId>/<charId>.png`. Next.js serves from `/public`
//     directly so the dashboard can render the thumbnail with no extra route.
//
// Idempotency:
//   - Re-registering the same character (same userId + same fullPrompt) is a
//     no-op — we update `previewUrl` if the existing row had none, otherwise
//     return the existing row untouched.
//   - The DB row's id is generated by Prisma; we use that id as the public
//     filename so future deletes / overwrites are easy to reason about.

import fs from "fs/promises";
import fsSync from "fs";
import path from "path";
import { db } from "@/lib/db";
import { createLogger } from "@/lib/logger";

const log = createLogger("FlowTV:CharLib");

const PUBLIC_BASE_DIR = path.join(process.cwd(), "public", "characters");

export interface FlowTvCharacterSummary {
  id: string;
  name: string;
  niche: string | null;
  language: string | null;
  characterStyle: string | null;
  previewUrl: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface FlowTvCharacterFull extends FlowTvCharacterSummary {
  fullPrompt: string;
  /** Absolute filesystem path to the on-disk png (under /public/characters/...). */
  absolutePath: string | null;
}

interface RegisterOpts {
  userId: string;
  /** Disk path of the just-rendered/adopted Phase 1 character image. */
  characterPath: string;
  /** Human-readable label, usually the storyline title. */
  name: string;
  /** Full Gemini-emitted character prompt (becomes Character.fullPrompt). */
  fullPrompt: string;
  niche: string;
  language: string;
  characterStyle: string;
}

/**
 * Upsert a `Character` row for a Flow TV character image. Returns the row's
 * id (existing or new). Best-effort: failures here MUST NOT abort the
 * Phase 1 pipeline — we just log and bail.
 */
export async function registerFlowTvCharacter(
  opts: RegisterOpts,
): Promise<string | null> {
  if (!opts.userId || !opts.characterPath) return null;
  if (!fsSync.existsSync(opts.characterPath)) {
    log.warn(
      `registerFlowTvCharacter: source image missing — ${opts.characterPath}`,
    );
    return null;
  }

  try {
    const prompt = (opts.fullPrompt ?? "").trim();
    if (prompt.length < 20) {
      log.warn(
        `registerFlowTvCharacter: prompt too short for "${opts.name}", skipping registry`,
      );
      return null;
    }

    // Idempotency: avoid duplicating a row when the same character is
    // re-rendered across runs. Match on (userId + first 200 chars of prompt)
    // rather than exact equality so trailing whitespace doesn't fork.
    const promptKey = prompt.slice(0, 200);
    const existing = await db.character.findFirst({
      where: {
        userId: opts.userId,
        type: "flow_tv",
        fullPrompt: { startsWith: promptKey },
      },
      orderBy: { updatedAt: "desc" },
    });

    let charId: string;
    if (existing) {
      charId = existing.id;
      // If existing row has no preview, refresh from this run's image.
      if (!existing.previewUrl) {
        const previewUrl = await copyToPublic(
          opts.userId,
          charId,
          opts.characterPath,
        );
        await db.character.update({
          where: { id: charId },
          data: { previewUrl, name: opts.name },
        });
        log.log(`Backfilled preview for existing flow-tv character ${charId}`);
      }
    } else {
      const created = await db.character.create({
        data: {
          userId: opts.userId,
          name: opts.name,
          type: "flow_tv",
          fullPrompt: prompt,
          // We embed metadata in the existing schema fields rather than
          // adding columns. `physical` carries niche, `clothing` language,
          // `accessories` characterStyle. That keeps Prisma migrations off
          // the table for now.
          physical: opts.niche,
          clothing: opts.language,
          accessories: opts.characterStyle,
        },
      });
      charId = created.id;
      const previewUrl = await copyToPublic(
        opts.userId,
        charId,
        opts.characterPath,
      );
      await db.character.update({
        where: { id: charId },
        data: { previewUrl },
      });
      log.log(`Registered flow-tv character ${charId} ("${opts.name}")`);
    }
    return charId;
  } catch (e) {
    log.error(
      `registerFlowTvCharacter failed: ${(e as Error).message?.slice(0, 200)}`,
    );
    return null;
  }
}

async function copyToPublic(
  userId: string,
  charId: string,
  srcPath: string,
): Promise<string> {
  const userDir = path.join(PUBLIC_BASE_DIR, userId);
  await fs.mkdir(userDir, { recursive: true });
  const ext = (path.extname(srcPath) || ".png").toLowerCase();
  const destFile = `${charId}${ext}`;
  const destPath = path.join(userDir, destFile);
  await fs.copyFile(srcPath, destPath);
  return `/characters/${userId}/${destFile}`;
}

/**
 * One-shot backfill: scan the user's persisted FlowRun states for runs that
 * have a `characterPath` on disk and a storyline.characterPrompt, but no
 * matching DB row yet, and register them. Returns the count of new rows
 * created. Best-effort; a failure here logs and returns 0.
 */
export async function backfillFlowTvCharactersFromRuns(
  userId: string,
): Promise<number> {
  try {
    const { listRuns } = await import("@/services/flow-tv-run");
    const runs = await listRuns({ userId });
    let created = 0;
    for (const r of runs) {
      const charPath = r.characterPath;
      const prompt = r.storyline?.characterPrompt;
      const title = r.storyline?.title;
      if (!charPath || !prompt || !title) continue;
      if (!fsSync.existsSync(charPath)) continue;
      // registerFlowTvCharacter is idempotent (matches on prompt prefix), so
      // calling it for every run is safe.
      const id = await registerFlowTvCharacter({
        userId,
        characterPath: charPath,
        name: title,
        fullPrompt: prompt,
        niche: r.niche ?? "unknown",
        language: r.language ?? "unknown",
        characterStyle: r.characterStyle ?? "unknown",
      });
      if (id) created += 1;
    }
    return created;
  } catch (e) {
    log.warn(
      `backfillFlowTvCharactersFromRuns failed: ${(e as Error).message?.slice(0, 200)}`,
    );
    return 0;
  }
}

/**
 * List all `flow_tv`-typed characters owned by the user, newest first.
 */
export async function listFlowTvCharacters(
  userId: string,
): Promise<FlowTvCharacterSummary[]> {
  const rows = await db.character.findMany({
    where: { userId, type: "flow_tv" },
    orderBy: { updatedAt: "desc" },
    select: {
      id: true,
      name: true,
      physical: true,
      clothing: true,
      accessories: true,
      previewUrl: true,
      createdAt: true,
      updatedAt: true,
    },
  });
  return rows.map((r) => ({
    id: r.id,
    name: r.name,
    niche: r.physical,
    language: r.clothing,
    characterStyle: r.accessories,
    previewUrl: r.previewUrl,
    createdAt: r.createdAt,
    updatedAt: r.updatedAt,
  }));
}

/**
 * Fetch a single Flow TV character with its full prompt and absolute path.
 * Returns null if the character doesn't belong to the user or if it isn't a
 * `flow_tv`-typed row.
 */
export async function loadFlowTvCharacter(
  characterId: string,
  userId: string,
): Promise<FlowTvCharacterFull | null> {
  const row = await db.character.findUnique({ where: { id: characterId } });
  if (!row || row.userId !== userId || row.type !== "flow_tv") return null;

  let absolutePath: string | null = null;
  if (row.previewUrl) {
    const rel = row.previewUrl.replace(/^\/+/, "");
    const candidate = path.join(process.cwd(), "public", rel);
    if (fsSync.existsSync(candidate)) absolutePath = candidate;
  }

  return {
    id: row.id,
    name: row.name,
    niche: row.physical,
    language: row.clothing,
    characterStyle: row.accessories,
    previewUrl: row.previewUrl,
    fullPrompt: row.fullPrompt,
    createdAt: row.createdAt,
    updatedAt: row.updatedAt,
    absolutePath,
  };
}
