import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — NarrateAI",
  description: "Terms and conditions governing the use of the NarrateAI platform.",
};

export default function TermsOfServicePage() {
  return (
    <article className="mx-auto max-w-3xl px-6 py-16 prose prose-neutral dark:prose-invert">
      <Link href="/" className="text-sm text-muted-foreground no-underline hover:text-foreground mb-8 block">
        &larr; Back to Home
      </Link>

      <h1>Terms of Service</h1>
      <p className="lead">
        Last updated: <time dateTime="2026-03-25">March 25, 2026</time>
      </p>

      <p>
        Please read these Terms of Service (&quot;Terms&quot;) carefully before
        using the NarrateAI platform (&quot;Service&quot;) operated by NarrateAI
        (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;). By accessing or
        using the Service, you agree to be bound by these Terms.
      </p>

      <h2>1. Eligibility</h2>
      <p>
        You must be at least 16 years old to use the Service. By creating an
        account, you represent and warrant that you meet this age requirement
        and have the legal capacity to enter into these Terms.
      </p>

      <h2>2. Account Responsibilities</h2>
      <ul>
        <li>
          You are responsible for maintaining the confidentiality of your
          account credentials and for all activity under your account.
        </li>
        <li>
          You agree to provide accurate and complete information when creating
          your account and to keep it up to date.
        </li>
        <li>
          You must notify us immediately if you suspect unauthorized access to
          your account.
        </li>
      </ul>

      <h2>3. Acceptable Use</h2>
      <p>You agree not to use the Service to:</p>
      <ul>
        <li>
          Generate, distribute, or promote content that is illegal, harmful,
          threatening, abusive, defamatory, obscene, or otherwise
          objectionable.
        </li>
        <li>
          Infringe on any third party&apos;s intellectual property rights,
          including copyrights, trademarks, or trade secrets.
        </li>
        <li>
          Impersonate any person or entity, or falsely state or misrepresent
          your affiliation with a person or entity.
        </li>
        <li>
          Attempt to gain unauthorized access to the Service, other accounts,
          computer systems, or networks connected to the Service.
        </li>
        <li>
          Use the Service to send spam, bulk unsolicited messages, or
          automated content designed to manipulate platform algorithms.
        </li>
        <li>
          Reverse-engineer, decompile, or disassemble any aspect of the
          Service.
        </li>
      </ul>

      <h2>4. Content Ownership &amp; License</h2>

      <h3>4.1 Your Content</h3>
      <p>
        You retain ownership of the content you create or upload through the
        Service (scripts, videos, images, voiceovers, etc.). By using the
        Service, you grant us a limited, non-exclusive license to process,
        store, and transmit your content solely for the purpose of operating
        the Service (e.g., generating videos, publishing to social platforms
        you authorize).
      </p>

      <h3>4.2 AI-Generated Content</h3>
      <p>
        Content generated by AI models through the Service is provided
        &quot;as-is.&quot; You are solely responsible for reviewing
        AI-generated content before publishing and ensuring it complies with
        applicable laws and the terms of the social platforms where it is
        posted.
      </p>

      <h3>4.3 Source Content &amp; Copyright</h3>
      <p>
        When using the clip repurposing feature, you are responsible for
        ensuring that the source material you select for repurposing is either
        in the public domain, licensed for reuse, or that your use qualifies
        as fair use under applicable law. We do not guarantee that discovered
        content is free of copyright restrictions.
      </p>

      <h2>5. Third-Party Platforms</h2>
      <p>
        The Service integrates with third-party platforms (YouTube, Facebook,
        Instagram, TikTok, etc.). Your use of these platforms through our
        Service is also governed by their respective terms of service and
        policies. We are not responsible for the actions, policies, or
        practices of these platforms.
      </p>

      <h2>6. Service Availability</h2>
      <p>
        We strive to maintain high availability but do not guarantee
        uninterrupted access. The Service may be temporarily unavailable due
        to maintenance, updates, or circumstances beyond our control. We are
        not liable for any loss or damage resulting from Service downtime.
      </p>

      <h2>7. Limitation of Liability</h2>
      <p>
        To the fullest extent permitted by law, NarrateAI and its affiliates,
        officers, employees, and agents shall not be liable for any indirect,
        incidental, special, consequential, or punitive damages, including
        loss of profits, data, or goodwill, arising from your use of or
        inability to use the Service.
      </p>
      <p>
        Our total aggregate liability for any claims arising from or related
        to the Service shall not exceed the amount you paid us in the twelve
        (12) months preceding the claim.
      </p>

      <h2>8. Disclaimers</h2>
      <ul>
        <li>
          The Service is provided &quot;as is&quot; and &quot;as available&quot;
          without warranties of any kind, express or implied.
        </li>
        <li>
          We do not warrant that AI-generated content will be accurate,
          complete, or suitable for any particular purpose.
        </li>
        <li>
          View predictions, trending scores, and analytics provided by the
          Service are estimates only and should not be relied upon as
          guarantees of performance.
        </li>
      </ul>

      <h2>9. Termination</h2>
      <p>
        We may suspend or terminate your account at any time if we reasonably
        believe you have violated these Terms. You may delete your account at
        any time through the Settings page. Upon termination, your right to
        use the Service ceases immediately, and we may delete your data in
        accordance with our{" "}
        <Link href="/privacy">Privacy Policy</Link>.
      </p>

      <h2>10. Changes to These Terms</h2>
      <p>
        We reserve the right to modify these Terms at any time. We will
        provide notice of material changes by updating the &quot;Last
        updated&quot; date and, where appropriate, notifying you via email or
        an in-app notice. Continued use of the Service after changes take
        effect constitutes acceptance of the updated Terms.
      </p>

      <h2>11. Governing Law</h2>
      <p>
        These Terms shall be governed by and construed in accordance with the
        laws of the jurisdiction in which NarrateAI is incorporated, without
        regard to its conflict-of-law provisions.
      </p>

      <h2>12. Contact</h2>
      <p>
        For questions about these Terms, please contact us at{" "}
        <a href="mailto:legal@narrateai.com">legal@narrateai.com</a>.
      </p>
    </article>
  );
}
