export type AspectRatio = "9:16" | "16:9";

export interface Niche {
  id: string;
  name: string;
  icon: string;
  description: string;
  sampleTopics: string[];
  defaultTone: string;
  defaultArtStyle: string;
  defaultMusic: string;
  /** When set, videos in this niche use this aspect ratio (e.g. 16:9 for cinematic storytelling). Default 9:16. */
  aspectRatio?: AspectRatio;
  /** Max duration in seconds for this niche (e.g. 600 = 10 min for long-form). Default 120. */
  maxDuration?: number;
  /** Min duration in seconds for this niche. Default 15. */
  minDuration?: number;
}

export const NICHES: Niche[] = [
  {
    id: "scary-stories",
    name: "Scary Stories",
    icon: "👻",
    description: "Terrifying tales that keep viewers on the edge",
    sampleTopics: [
      "The haunted lighthouse keeper",
      "Voices from the basement",
      "The doll that moved at night",
      "The cabin that wasn't on any map",
      "A knock at 3:33 AM every night",
      "The mirror that showed someone else",
      "The elevator that goes to a floor that doesn't exist",
      "Why hikers vanish on this one trail",
      "The radio station that broadcasts from nowhere",
      "The email from a dead friend's account",
      "The house sitter who wasn't alone",
      "The camera footage nobody can explain",
      "The town that evacuated overnight and never came back",
      "The child's drawing that predicted the future",
      "The phone call from inside the walls",
      "The last voicemail before she vanished",
      "Something lives in the space between floors",
      "The sleep paralysis entity across cultures",
      "The subway station that was sealed shut in 1941",
      "The cursed painting that ruins every owner",
    ],
    defaultTone: "dramatic",
    defaultArtStyle: "dark-cinematic",
    defaultMusic: "dramatic",
  },
  {
    id: "mythology",
    name: "Mythology",
    icon: "⚡",
    description: "Epic myths and legends from around the world",
    sampleTopics: [
      "The fall of Icarus",
      "Ragnarok - the twilight of the gods",
      "Medusa's curse and Perseus",
      "Pandora's box and what was left inside",
      "Orpheus and the journey to the underworld",
      "The labors of Hercules - the one that broke him",
      "Sisyphus and the boulder",
      "Narcissus and the pool",
      "Prometheus and the stolen fire",
      "The Trojan horse - what really happened that night",
      "Odysseus and the cyclops",
      "Echo and the curse of repetition",
    ],
    defaultTone: "dramatic",
    defaultArtStyle: "oil-painting",
    defaultMusic: "dramatic",
  },
  {
    id: "history",
    name: "History",
    icon: "📜",
    description: "Fascinating moments from history that changed the world",
    sampleTopics: [
      "The last day of Pompeii — hour by hour",
      "The mystery of the Bermuda Triangle disappearances",
      "The real story behind the Titanic's sinking — not the movie version",
      "The assassination of Archduke Franz Ferdinand that started WWI",
      "Cleopatra lived closer to the iPhone than to the pyramids",
      "The samurai who became the first Japanese man in Europe",
      "The night the Berlin Wall fell — told by those who were there",
      "The Chernobyl disaster — the 36 hours that changed the world",
      "The Library of Alexandria — what was really lost",
      "The Aztec empire's fall — disease killed 90% before soldiers arrived",
      "The real Spartans — were they really that tough",
      "The first photograph ever taken — and what it reveals",
      "The Great Fire of London — how a baker destroyed a city",
      "Napoleon's disastrous invasion of Russia — 600,000 men, 27,000 returned",
      "The Underground Railroad — the secret routes to freedom",
      "The Rosetta Stone — how a rock unlocked an entire civilization",
      "The Viking discovery of America 500 years before Columbus",
      "The Black Death — how a plague killed half of Europe",
      "The Space Race — the moments that defined the Cold War",
      "The invention of penicillin — the accident that saved billions",
    ],
    defaultTone: "educational",
    defaultArtStyle: "realistic",
    defaultMusic: "ambient",
  },
  {
    id: "true-crime",
    name: "True Crime",
    icon: "🔍",
    description: "Real criminal cases and unsolved mysteries",
    sampleTopics: [
      "The world's greatest unsolved heist",
      "The disappearance that baffled police for decades",
      "A cold case cracked after 30 years by DNA",
      "The serial killer who hid in plain sight as a clown",
      "The diamond thief who beat the world's best vault",
      "The cult leader who convinced a town to vanish",
      "The wrongfully convicted man freed after 25 years",
      "The forger who fooled every art museum in Europe",
      "The kidnapping that was actually an insurance scam",
      "The poisoner nobody suspected — a family doctor",
      "The hitman who turned FBI informant",
      "The double life of a suburban school teacher",
      "The bank robbery planned entirely on Reddit",
      "The body found in the chimney 7 years later",
      "The witness protection failure that cost three lives",
      "The identity thief who became a surgeon",
      "The hiker who vanished on a GPS-tracked trail",
      "The arsonist firefighter who set 100 fires",
      "The jewel heist through the sewer system",
      "The case solved by a victim's smartwatch data",
    ],
    defaultTone: "dramatic",
    defaultArtStyle: "dark-cinematic",
    defaultMusic: "dramatic",
  },
  {
    id: "anime-recaps",
    name: "Anime Recaps",
    icon: "🎌",
    description: "Exciting anime story recaps and breakdowns",
    sampleTopics: [
      "The most overpowered anime villain nobody talks about",
      "A hero's sacrifice that shocked the entire fandom",
      "The greatest anime plot twist ever written",
      "The side character who deserved their own show",
      "The anime rivalry that defined a generation",
      "The training arc that pushed a character past their limit",
      "The mentor death that hit harder than any fight scene",
      "The redemption arc that made everyone forgive the villain",
      "The forgotten anime that predicted real-world events",
      "The anime power system that actually makes logical sense",
      "The filler arc that accidentally became canon",
      "The backstory reveal that recontextualized the entire series",
      "The anime ending that divided the entire fanbase",
      "The crossover episode that broke the internet",
      "The weakest character who won the strongest fight",
      "The anime that was cancelled too soon — what would have happened",
      "The tournament arc that changed shonen forever",
      "The female character who carried the entire show",
      "The quiet moment in anime that hit harder than any battle",
      "The anime opening that spoiled everything",
    ],
    defaultTone: "casual",
    defaultArtStyle: "anime",
    defaultMusic: "upbeat",
  },
  {
    id: "life-hacks",
    name: "Life Hacks",
    icon: "💡",
    description: "Clever tips and tricks to make life easier",
    sampleTopics: [
      "5 phone tricks you didn't know existed until now",
      "How to save $500 this month with zero sacrifice",
      "Kitchen hacks that actually work — tested by chefs",
      "The 2-minute rule that eliminates procrastination",
      "How to fall asleep in under 60 seconds — military method",
      "5 negotiation tricks to get a lower price on anything",
      "The freezer hack that keeps bread fresh for months",
      "How to remove any stain with stuff already in your kitchen",
      "The battery trick that tells you if it's dead instantly",
      "5 packing hacks that fit twice as much in your suitcase",
      "The toothpaste trick that fixes scratched phone screens",
      "How to charge your phone 50% faster with one setting",
      "The binder clip hacks that organize your entire desk",
      "How to unclog a drain without chemicals in 30 seconds",
      "The rubber band hack that opens any stuck jar",
      "5 Google search tricks that change how you find anything",
      "The ice cube tray hacks for meal prep and organization",
      "How to iron clothes without an iron — 3 methods",
      "The WD-40 hacks you never knew about",
      "How to remember anyone's name after hearing it once",
    ],
    defaultTone: "casual",
    defaultArtStyle: "pixar-3d",
    defaultMusic: "upbeat",
  },
  {
    id: "motivation",
    name: "Motivation",
    icon: "🔥",
    description: "Inspiring stories and motivational content",
    sampleTopics: [
      "From homeless to billionaire — the real story",
      "The athlete who never gave up after losing both legs",
      "Why your failures are your superpower — the science",
      "The 5 AM club — why waking up early changes everything",
      "The speech that made an entire stadium cry",
      "Why comfort zones are where dreams go to die",
      "The war veteran who built schools in 12 countries",
      "The 10-second rule that kills fear and builds courage",
      "The teacher who believed in the kid nobody else would",
      "Why discipline will always beat motivation",
      "The painter who lost her hands and kept painting with her mouth",
      "The 1% daily improvement rule — 37x better in one year",
      "The astronaut who failed 15 times before getting selected",
      "Why most people quit right before the breakthrough",
      "The marathon runner who collapsed and crawled to the finish",
      "The power of writing your goals down — the Harvard study",
      "The immigrant who learned English in 6 months and built a tech startup",
      "Why comparison is the thief of joy — and how to stop",
      "The 60-year-old who got a PhD after being told she was too old",
      "Burn the boats — the ancient strategy that guarantees success",
    ],
    defaultTone: "dramatic",
    defaultArtStyle: "realistic",
    defaultMusic: "dramatic",
  },
  {
    id: "science-facts",
    name: "Science Facts",
    icon: "🔬",
    description: "Mind-blowing science facts and discoveries",
    sampleTopics: [
      "What happens at the edge of the universe",
      "The parasite that controls minds",
      "Why time moves differently in space",
      "The creature that can survive in lava",
      "Why your brain deletes half of what you see",
      "The island that appears and disappears",
      "What happens inside a dying star",
      "The fish that walks on land",
      "Why some people hear colors",
      "The fungus that turns ants into zombies",
      "What we still don't know about sleep",
      "The deepest place on Earth and what lives there",
    ],
    defaultTone: "educational",
    defaultArtStyle: "realistic",
    defaultMusic: "ambient",
  },
  {
    id: "conspiracy-theories",
    name: "Conspiracy Theories",
    icon: "🕵️",
    description: "The most intriguing conspiracy theories explored",
    sampleTopics: [
      "The hidden city under Antarctica ice",
      "The simulation theory — are we living in a program",
      "The secret space program they never declassified",
      "The Bermuda Triangle's real explanation the Navy buried",
      "The fake moon landing theory — debunked or confirmed",
      "Project MKUltra and CIA mind control experiments",
      "The Denver Airport tunnels and their murals",
      "The Mandela Effect — proof of parallel timelines",
      "Area 51's neighbor: the base that doesn't officially exist",
      "The missing Malaysian Airlines flight — what really happened",
      "Operation Paperclip: when America hired Nazi scientists",
      "The Dead Internet Theory — are most users bots now",
      "The Philadelphia Experiment — did a ship really teleport",
      "Why certain inventions disappear after the patent is filed",
      "The Dyatlov Pass incident — no official explanation fits",
      "HAARP and weather control — science or conspiracy",
      "The Georgia Guidestones and their mysterious destruction",
      "The Voynich Manuscript — a 600-year unsolved code",
      "The Black Knight satellite orbiting Earth for 13,000 years",
      "The Tartarian Empire that was erased from history books",
    ],
    defaultTone: "dramatic",
    defaultArtStyle: "dark-cinematic",
    defaultMusic: "dramatic",
  },
  {
    id: "religious-epics",
    name: "Religious Epics",
    icon: "🙏",
    description: "Powerful sacred stories from every faith — Bible, Mahabharata, Quran, Buddhist tales",
    sampleTopics: [
      "David vs Goliath - the ultimate underdog",
      "Krishna's lesson to Arjuna on the battlefield",
      "The night journey of Prophet Muhammad",
      "Buddha's path to enlightenment",
      "Noah's ark and the great flood",
    ],
    defaultTone: "dramatic",
    defaultArtStyle: "oil-painting",
    defaultMusic: "dramatic",
  },
  {
    id: "what-if",
    name: "What If",
    icon: "🤔",
    description: "Mind-bending hypothetical scenarios that make you question reality",
    sampleTopics: [
      "What if gravity stopped for 5 seconds",
      "What if the sun disappeared right now",
      "What if humans could fly",
      "What if we could breathe underwater",
      "What if the internet vanished forever",
      "What if you could only tell the truth for 24 hours",
      "What if time ran backward for one day",
      "What if every lie you ever told came true",
      "What if animals could talk to humans",
      "What if you woke up with no memory",
      "What if money had no value tomorrow",
      "What if we discovered we're not alone tonight",
      "What if you could only use one sense for a week",
      "What if the moon suddenly got 10x closer",
      "What if plants could feel pain",
    ],
    defaultTone: "educational",
    defaultArtStyle: "realistic",
    defaultMusic: "dramatic",
  },
  {
    id: "dark-psychology",
    name: "Dark Psychology",
    icon: "🧠",
    description: "Hidden manipulation tactics, mind tricks, and the dark side of human behavior",
    sampleTopics: [
      "5 manipulation tricks narcissists use on you daily",
      "Why you always pick the middle option — the decoy effect",
      "The psychology trick that makes people obey authority",
      "The sunk cost fallacy — why you stay in bad relationships",
      "Love bombing: the first stage of emotional abuse",
      "How advertisers hack your brain with anchoring bias",
      "The dark triad personality — psychopathy, narcissism, Machiavellianism",
      "Gaslighting phrases people use without realizing",
      "The Benjamin Franklin effect — make enemies like you",
      "Why silence is the most powerful response to manipulation",
      "The 48 Laws of Power condensed — the 5 darkest rules",
      "The bystander effect — why nobody helps in a crowd",
      "Mirroring: the manipulation tactic that feels like connection",
      "The IKEA effect — why you overvalue what you built yourself",
      "How cults recruit intelligent people using gradual commitment",
      "The halo effect — why attractive people get away with more",
      "Intermittent reinforcement — the slot machine of toxic love",
      "The door-in-the-face technique used by salespeople and politicians",
      "Why your brain remembers insults longer than compliments — negativity bias",
      "The Dunning-Kruger effect — when the least skilled are most confident",
    ],
    defaultTone: "dramatic",
    defaultArtStyle: "dark-cinematic",
    defaultMusic: "dramatic",
  },
  {
    id: "space-cosmos",
    name: "Space & Cosmos",
    icon: "🌌",
    description: "The mind-blowing wonders of space, galaxies, and the universe",
    sampleTopics: [
      "What's inside a black hole — spaghettification explained",
      "The scariest planet ever discovered — raining glass sideways",
      "Why we might be alone in the galaxy — the Great Filter",
      "The Voyager golden record — a message to aliens",
      "The rogue planet wandering through space without a star",
      "Neutron stars: a teaspoon weighs a billion tons",
      "The Bootes Void — the emptiest place in the universe",
      "What happens when two galaxies collide — Milkomeda",
      "The star that shouldn't exist — it's older than the universe",
      "Magnetars: the most powerful magnets in the cosmos",
      "The pale blue dot — Earth from 6 billion km away",
      "The sound of a black hole — NASA's actual recording",
      "Olympus Mons: the volcano 3 times taller than Everest on Mars",
      "The cosmic microwave background — the oldest light in existence",
      "Tabby's Star — the alien megastructure mystery",
      "What would happen if you fell into Jupiter",
      "The Fermi Paradox — where is everybody",
      "The diamond planet twice the size of Earth",
      "Panspermia: did life on Earth come from space",
      "The heat death of the universe — how everything ends",
    ],
    defaultTone: "dramatic",
    defaultArtStyle: "realistic",
    defaultMusic: "dramatic",
  },
  {
    id: "animal-kingdom",
    name: "Animal Kingdom",
    icon: "🦁",
    description: "Incredible animal facts, behaviors, and nature's wildest moments",
    sampleTopics: [
      "The tardigrade — the only animal that can survive in space",
      "Why octopuses have three hearts and blue blood",
      "The mosquito — the deadliest creature on Earth kills millions",
      "The pistol shrimp snaps so hard it creates a flash of light",
      "The mimic octopus can impersonate 15 different species",
      "Crows remember human faces and hold grudges for years",
      "The axolotl can regrow its brain, heart, and limbs",
      "The honey badger fears nothing — not even lions or cobras",
      "The deep-sea anglerfish and its horrifying mating ritual",
      "Why flamingos are actually born white, not pink",
      "The bombardier beetle shoots boiling chemicals from its body",
      "The lyrebird can perfectly mimic chainsaws and camera shutters",
      "Dolphins sleep with one eye open — literally",
      "The immortal jellyfish that reverses its own aging",
      "The African wild dog has a 80% hunt success rate — lions only 25%",
      "The archer fish spits water to knock insects out of trees",
      "The leafcutter ant runs the world's oldest farming operation",
      "The mantis shrimp sees 16 colors — humans see only 3",
      "The parasitic wasp that turns cockroaches into zombies",
      "The electric eel generates enough voltage to power 10 light bulbs",
      "The narwhal's tusk is actually a giant inside-out tooth",
      "Elephants mourn their dead and visit old bones",
      "The peregrine falcon dives at 390 km/h — the fastest animal alive",
      "The naked mole rat is immune to cancer and feels no pain",
    ],
    defaultTone: "educational",
    defaultArtStyle: "realistic",
    defaultMusic: "ambient",
  },
  {
    id: "survival",
    name: "Survival",
    icon: "⚠️",
    description: "How to survive impossible situations and real disaster stories",
    sampleTopics: [
      "How to survive a plane crash — the 90-second rule",
      "The man who survived 76 days lost at sea on a raft",
      "What to do if you fall into quicksand — stop struggling",
      "How to survive an elevator free-fall — there IS a way",
      "The couple who survived 66 days in the Amazon after a plane crash",
      "How to survive a bear attack — grizzly vs black bear rules",
      "The climber who cut off his own arm to escape a boulder",
      "How to survive a lightning strike — and why it hits twice",
      "The family trapped in a car underwater — the escape technique",
      "Surviving an avalanche — you have 15 minutes of air",
      "The sailor who drifted 438 days across the Pacific alone",
      "How to survive a volcanic eruption — the lahar is the real killer",
      "The hiker who survived 3 weeks eating bugs and bark",
      "Surviving a riptide — swim parallel, never against it",
      "The pilot who landed on the Hudson River with no engines",
      "How to survive a wildfire — the counterintuitive escape route",
      "The mountaineers stuck above 8000m — the death zone rules",
      "Surviving a sinking ship — what Titanic survivors did differently",
      "The freediver who blacked out at 100 meters and lived",
      "How to survive a tornado if you're caught outside",
    ],
    defaultTone: "dramatic",
    defaultArtStyle: "realistic",
    defaultMusic: "dramatic",
  },
  {
    id: "money-wealth",
    name: "Money & Wealth",
    icon: "💎",
    description: "How the rich think, wealth secrets, and the psychology of money",
    sampleTopics: [
      "How billionaires actually spend the first hour of their day",
      "The $1 rule that completely changed how I think about money",
      "Why rich people never work for money — they make money work",
      "The latte factor — how small spending adds up to millions",
      "The 50/30/20 budget rule that millionaires actually follow",
      "Why lottery winners go broke within 5 years",
      "The psychological difference between rich and poor thinking",
      "Compound interest: the 8th wonder of the world — Einstein",
      "The side hustles that actually built generational wealth",
      "How the wealthy use debt as a tool — good debt vs bad debt",
      "The 10x rule: why thinking big changes everything about money",
      "Why most millionaires drive used cars — stealth wealth explained",
      "The pay-yourself-first principle — and why 90% of people skip it",
      "How real estate leverage creates more millionaires than anything else",
      "The Warren Buffett rule: never lose money — here's how",
      "Why your savings account is secretly losing you money to inflation",
      "The Pareto principle in wealth — 80% of results from 20% of effort",
      "How tax loopholes legally save the rich millions every year",
      "The 72-hour rule that stops impulse spending permanently",
      "The monk who became a billionaire — money mindset from zero",
    ],
    defaultTone: "dramatic",
    defaultArtStyle: "realistic",
    defaultMusic: "dramatic",
  },
  {
    id: "funny-stories",
    name: "Funny Stories",
    icon: "😂",
    description: "Hilarious jokes, dad jokes, and comedy sketches that make viewers laugh",
    sampleTopics: [
      "The worst dad joke that actually made the whole room laugh",
      "When autocorrect sent the most embarrassing text to the boss",
      "The job interview that went hilariously wrong in every way",
      "The roommate who cooked ramen in a coffee maker for a year",
      "The wedding speech that accidentally roasted everyone",
      "The dog who crashed a live news broadcast and became famous",
      "The GPS that led a family into a lake",
      "The office prank war that got completely out of hand",
      "The grandma who accidentally joined a group video call naked",
      "The pizza delivery guy who saved a hostage situation",
      "The student who submitted a meme as their final essay — and passed",
      "The cat who locked its owner out of the car in a parking lot",
      "The worst first date in history — she brought her parrot",
      "The neighbor dispute over a garden gnome that went to court",
      "The kid who ordered 94 pizzas on his mom's credit card",
      "The man who accidentally RSVP'd to a stranger's wedding and went",
      "The airline that lost someone's luggage and found it 11 years later",
      "The teacher who accidentally played the wrong video in class",
      "The self-checkout machine that called security for buying bananas",
      "The family reunion where nobody recognized each other after lockdown",
    ],
    defaultTone: "funny",
    defaultArtStyle: "pixar-3d",
    defaultMusic: "upbeat",
  },
  {
    id: "zero-to-hero",
    name: "Zero to Hero",
    icon: "🚀",
    description: "Underdog stories of people who turned rock bottom into greatness",
    sampleTopics: [
      "Sleeping in his car to owning a billion-dollar company",
      "Rejected 300 times then became a publishing legend",
      "From village nobody to global icon — no connections, no money",
      "The janitor who became a millionaire inventor",
      "Fired at 30, founded a tech empire at 35",
      "The blind musician who sold out stadiums worldwide",
      "From prison to CEO — the redemption nobody believed",
      "The refugee who walked 3000 miles and became a surgeon",
      "The high school dropout who built a fashion empire",
      "The bankrupt farmer who invented something worth billions",
      "From homeless shelter to Harvard — the essay that changed everything",
      "The single mom who coded her way to Silicon Valley",
      "The stuttering kid who became the world's greatest orator",
      "Paralyzed at 19, ran a marathon by 25 — how",
      "The failed restaurant owner who created a global food chain",
      "The soldier who lost both legs and climbed Everest",
      "From sleeping on subway trains to winning a Grammy",
      "The dyslexic kid they said would never read — now a bestselling author",
      "Orphaned at 8, billionaire by 40 — the untold story",
      "The street vendor who outsmarted Wall Street traders",
    ],
    defaultTone: "dramatic",
    defaultArtStyle: "realistic",
    defaultMusic: "dramatic",
  },
  {
    id: "character-storytelling",
    name: "Character Storytelling",
    icon: "🎬",
    description: "Character-centric narratives with emotional hooks, drama, and BGM. Cinematic 16:9 format; story length is flexible (30s to 10 min). Best with a recurring character (Star mode).",
    sampleTopics: [
      "A lone warrior's last stand at the gate",
      "The moment she chose to walk away",
      "The letter that changed everything",
      "Two strangers on a train",
      "The day the silence broke",
    ],
    defaultTone: "dramatic",
    defaultArtStyle: "realistic",
    defaultMusic: "dramatic",
    aspectRatio: "16:9",
    minDuration: 30,
    maxDuration: 600,
  },
  {
    id: "satisfying",
    name: "Satisfying",
    icon: "✨",
    description: "Oddly satisfying visuals — cutting, slicing, pouring, perfect fits",
    sampleTopics: [
      "Perfectly cut soap and wax melting slowly",
      "Glass marbles rolling down impossible wooden tracks",
      "Hydraulic press crushing random objects in slow motion",
      "Kinetic sand being sliced with a razor-sharp knife",
      "Perfect calligraphy — every stroke lands exactly right",
      "Pressure washing decades of grime off concrete",
      "Pouring epoxy resin into a cracked river table",
      "Dominos falling in an intricate spiral pattern for 10 minutes",
      "Perfectly organized pantry — every jar and label aligned",
      "Cake decorating with mirror glaze — the pour is everything",
      "Flocking a car dashboard — the velvet transformation",
      "The perfect pancake flip in slow motion",
      "Laser cutting intricate patterns in wood and metal",
      "Pottery throwing on a wheel — from lump to vase",
      "Carpet cleaning the dirtiest rug back to brand new",
      "Ice cream rolls being made on a frozen plate",
      "A robot arm sorting thousands of colored balls by shade",
      "Restoring a rusty tool to mirror finish perfection",
      "The most satisfying 3D printing time-lapse ever",
      "Perfectly symmetrical tile laying — not a gap in sight",
    ],
    defaultTone: "casual",
    defaultArtStyle: "realistic",
    defaultMusic: "ambient",
  },
  {
    id: "moral-stories",
    name: "Moral Stories",
    icon: "📖",
    description: "Two-character animated fables with a clear life lesson — universal, timeless, shareable",
    sampleTopics: [
      "The fox who tricked the crow out of her cheese",
      "The tortoise who never quit the race",
      "Two wolves inside you — which one wins?",
      "The greedy monkey who couldn't let go of the jar",
      "The old man, his son, and the donkey",
      "The ant who laughed at the grasshopper",
      "The lion who was saved by a tiny mouse",
      "The boy who cried wolf one too many times",
      "The blind men and the elephant",
      "The scorpion and the frog crossing the river",
      "The oak tree and the reed in a storm",
      "The dog who lost his bone to his reflection",
    ],
    defaultTone: "educational",
    defaultArtStyle: "pixar-3d",
    defaultMusic: "ambient",
  },
  {
    id: "stoicism",
    name: "Stoicism",
    icon: "🏛️",
    description: "Stoic philosophy, sigma mindset, and ancient wisdom for an unshakable life",
    sampleTopics: [
      "Marcus Aurelius: control only what you can",
      "Why the strongest men walk alone",
      "7 stoic rules for an unshakable mind",
      "The art of not reacting — Epictetus",
      "Seneca on why busy people waste their lives",
      "How to be calm in chaos — stoic method",
      "The one habit that separates winners from losers",
      "Why comfort is the enemy of growth",
      "Stoic morning routine that changes everything",
      "The power of silence — why winners never explain",
      "Marcus Aurelius on dealing with difficult people",
      "Why discipline beats motivation every time",
    ],
    defaultTone: "dramatic",
    defaultArtStyle: "dark-cinematic",
    defaultMusic: "dramatic",
  },
  {
    id: "reddit-stories",
    name: "Reddit Stories",
    icon: "💬",
    description: "First-person confessional stories — drama, conflict, moral dilemmas from real life",
    sampleTopics: [
      "AITA for kicking out my roommate at 2am?",
      "My neighbor's secret camera was pointed at my window",
      "I found my boss's anonymous Reddit account",
      "TIFU by replying-all to 500 coworkers",
      "My date brought their mom to dinner",
      "I caught my best friend lying about me for years",
      "My landlord entered my apartment while I was sleeping",
      "I accidentally sent my diary to the family group chat",
      "My coworker stole my lunch for 6 months — here's how I caught them",
      "I discovered my parents' secret after 25 years",
      "My wedding was ruined by one uninvited guest",
      "I quit my dream job on day one — here's why",
    ],
    defaultTone: "casual",
    defaultArtStyle: "realistic",
    defaultMusic: "ambient",
  },
  {
    id: "country-comparison",
    name: "Country Comparison",
    icon: "🌍",
    description: "Country vs country showdowns — military, economy, culture, who would win?",
    sampleTopics: [
      "India vs China: who wins in 2025?",
      "USA vs Russia: military power compared",
      "Japan vs Germany: economy showdown",
      "Top 10 strongest armies in the world ranked",
      "Which country would survive an apocalypse?",
      "The richest vs the poorest country — side by side",
      "North Korea vs South Korea: the real difference",
      "Turkey vs Egypt: Mediterranean power battle",
      "Canada vs Australia: which is better to live in?",
      "The smallest country that could defeat a giant",
      "5 countries that will dominate by 2050",
      "Israel vs Iran: full military breakdown",
    ],
    defaultTone: "educational",
    defaultArtStyle: "realistic",
    defaultMusic: "dramatic",
  },
  {
    id: "quiz-challenge",
    name: "Quiz Challenge",
    icon: "❓",
    description: "Would you rather, trivia, and impossible dilemmas that make viewers comment",
    sampleTopics: [
      "Would you rather fly but only 1 foot high, or be invisible but sneeze every 10 seconds?",
      "Only 1% of people get all 5 right",
      "Guess the country from one weird law",
      "Two doors: one leads to wealth, one to wisdom — choose",
      "Would you rather know when you die or how you die?",
      "5 riddles that will break your brain",
      "Pick one superpower — but there's a catch",
      "Guess the price of these billionaire items",
      "Would you rather have $10 million or go back 10 years?",
      "The impossible food quiz — can you beat it?",
      "Would you rather be famous but hated or unknown but loved?",
      "Spot the fake fact — 3 truths, 1 lie",
    ],
    defaultTone: "casual",
    defaultArtStyle: "pixar-3d",
    defaultMusic: "upbeat",
  },
  {
    id: "brainrot",
    name: "Brainrot",
    icon: "🧠",
    description: "Rapid-fire mind-blowing facts in Gen Z style — fast, punchy, dopamine-hit content",
    sampleTopics: [
      "3 facts that will ruin your childhood",
      "Things your teacher never told you",
      "Why bananas are berries but strawberries aren't",
      "The country that technically doesn't exist",
      "Foods that are illegal in other countries",
      "Things that exist but shouldn't",
      "Your body does this while you sleep and it's wild",
      "Animals that break the laws of physics",
      "Places on Earth that don't feel real",
      "Historical facts that sound completely fake",
      "The dumbest laws that are still enforced",
      "Things we use every day that were invented by accident",
    ],
    defaultTone: "casual",
    defaultArtStyle: "realistic",
    defaultMusic: "upbeat",
  },
];

export function getNicheById(id: string): Niche | undefined {
  return NICHES.find((n) => n.id === id);
}

export function getDurationRangeForNiche(nicheId: string): { min: number; max: number } {
  const niche = getNicheById(nicheId);
  return {
    min: niche?.minDuration ?? 15,
    max: niche?.maxDuration ?? 120,
  };
}
